---
apiVersion: v2

name: ckic-manager
description: Caddy Kubernetes Ingress Controller Manager with a few catches

type: application

version: 0.22.0
appVersion: 0.23.0

icon: https://git.horse/uploads/-/system/project/avatar/177/ckic-avatar-takanashikiara-bluefield-twt-1.jpg

maintainers:
  - name: Vladimir Malinovskiy
    email: git@vprw.ru
    url: https://vapronva.pw
