---
replicaCount: 1

image:
  repository: rg.gl.vprw.ru
  image: vapronva/ckic/manager
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    memory: 20Mi
  requests:
    cpu: 5m
    memory: 10Mi

nodeSelector: {}
tolerations: []
affinity: {}

config:
  nodeLabel: ckic.cmld.ru/enabled
  configMapName: caddy-config
  configMapNamespace: caddy-system
  communicationMethod: clusterip  # or "direct"
  logLevel: info
  caddyImage: rg.gl.vprw.ru/oss-images/zerossl-caddy/caddy:2.9.1-alpine
  enableNodePort: true
  preferSavedState: false

defaultCaddyConfig: |
  {
    http_port 80
    https_port 443
    admin :2019
  }

  :80 {
    respond "Caddy is running! Default configuration."
  }
