---
replicaCount: 1

image:
  repository: rg.gl.vprw.ru
  image: vapronva/ckic/manager
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext:
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    memory: 20Mi
  requests:
    cpu: 5m
    memory: 10Mi

nodeSelector: {}
tolerations: []
affinity: {}

config:
  nodeLabel: ckic.cmld.ru/enabled
  configMapName: caddy-config
  configMapNamespace: caddy-system
  communicationMethod: clusterip  # or "direct"
  logLevel: info
  caddyImage: rg.gl.vprw.ru/oss-images/zerossl-caddy/caddy:2.9.1-alpine
  enableLoadBalancer: true
  preferSavedState: false
  secretName: caddy-env
  secretEnvKeys: []
  dataVolumePVC: caddy-data-lv
  configVolumePVC: caddy-config-lv
  externalEndpoints: []

caddyConfig:
  debug: true
  servers: ""
  global: |
    email {env.ACME_EMAIL}
    acme_dns powerdns {env.POWERDNS_SERVER_URL} {env.POWERDNS_API_TOKEN}
  global_optional: ""
  caddyfile: ""
  caddyfile_optional: ""
