---
stages:
  - test
  - build
  - post-test
  - publish

include:
  - component: $CI_SERVER_FQDN/ci/security/bundle@1
  - component: $CI_SERVER_FQDN/ci/golang/init-vet@2
  - component: $CI_SERVER_FQDN/ci/golang/lint@2
  - component: $CI_SERVER_FQDN/ci/golang/test@2
  - component: $CI_SERVER_FQDN/ci/docker/build-and-scan@4
    inputs:
      name: manager
      image: manager
      tags: latest,$CI_COMMIT_REF_NAME
      rules_changes:
        - Dockerfile
        - go.mod
        - "**/*.go"
        - $CI_CONFIG_PATH
  - component: $CI_SERVER_FQDN/ci/golang/build-binaries@2
    inputs:
      working_dir: cmd/manager
  - component: $CI_SERVER_FQDN/ci/helm-chart/lint@1
    inputs:
      job_name: validate + lint (helm chart)
      chart_dirs: .
      ct_args: --validate-chart-schema --validate-yaml --debug --validate-maintainers=false
  - component: $CI_SERVER_FQDN/ci/helm-chart/publish@1
    inputs:
      job_name: publish helm chart to gitlab registry
      charts_glob: chart
      lint_job_name: validate + lint (helm chart)

compile binaries:
  script:
    - build_binary "ckic-manager-$VERSION" linux amd64
    - build_binary "ckic-manager-$VERSION" linux arm64

.chart build and publish rules: &chart-build-and-publish-rules
  rules:
    - if: $CI_COMMIT_TAG

validate + lint (helm chart):
  <<:
    - *chart-build-and-publish-rules

publish helm chart to gitlab registry:
  <<:
    - *chart-build-and-publish-rules
  needs:
    - job: validate + lint (helm chart)
    - job: kics
      optional: true
