---
stages:
  - test
  - build
  - post-test
  - publish

variables:
  CT_IMAGE: ot.cmld.ru/quay.io/helmpack/chart-testing:v3.12.0

include:
  - component: gl.vprw.ru/ci/sast/sast@1
  - component: gl.vprw.ru/ci/sast/iac@1
  - component: gl.vprw.ru/ci/sast/bearer@1
    inputs:
      image: docker.io/bearer/bearer:latest
  - component: gl.vprw.ru/ci/secret-detection/sd@1
  - component: gl.vprw.ru/ci/golang/init-vet@1
    inputs:
      job_name: init + format + vet
      golang_version: "1.24"
  - component: gl.vprw.ru/ci/docker/build-buildah@2
    inputs:
      job_name: build container image
      job_name_manifest: push oci manifest
      ci_image_name: manager
      ci_image_tags: latest,$CI_COMMIT_REF_SLUG
      dockerfile_path: Dockerfile
  - component: gl.vprw.ru/ci/container-scanning/cs@1
    inputs:
      job_name: container scanning (latest)
      default_branch_image: $CI_REGISTRY_IMAGE/manager:latest
      application_repository: $CI_REGISTRY_IMAGE/manager
      application_tag: latest
  - component: gl.vprw.ru/ci/golang/build-binaries@1
    inputs:
      job_name: compile binaries
      working_dir: cmd/manager
      golang_version: "1.24"

go test:
  stage: test
  image: ot.cmld.ru/docker.io/library/golang:1.24
  needs:
    - job: init + format + vet
      artifacts: true
  script:
    - CGO_ENABLED=1 go test -race $(go list ./... | grep -v /vendor/)

.build rules: &build-rules
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - Dockerfile
        - .gitlab-ci.yml
        - go.mod
        - "**/*.go"
        - $CI_CONFIG_PATH

build container image:
  <<:
    - *build-rules

push oci manifest:
  <<:
    - *build-rules

compile binaries:
  <<:
    - *build-rules
  script:
    - build_binary "ckic-manager-$VERSION" linux amd64
    - build_binary "ckic-manager-$VERSION" linux arm64

container scanning (latest):
  <<: *build-rules
  needs:
    - job: build container image
    - job: push oci manifest

.chart build and publish rules: &chart-build-and-publish-rules
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - chart/**/*
        - $CI_CONFIG_PATH

validate + lint (helm chart):
  <<:
    - *chart-build-and-publish-rules
  stage: test
  image: $CT_IMAGE
  script:
    - cd "chart" || exit
    - ct lint --validate-chart-schema --validate-yaml --chart-dirs . --charts . --debug --validate-maintainers=false

publish helm chart to gitlab registry:
  <<:
    - *chart-build-and-publish-rules
  stage: publish
  image: $CT_IMAGE
  needs:
    - job: validate + lint (helm chart)
    - job: kics
      optional: true
  script:
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add --username gitlab-ci-token --password "$CI_JOB_TOKEN" "$CI_PROJECT_NAME" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/helm/stable"
    - helm package ./chart --destination ./packages
    - find ./packages -name "*.tgz" -print -exec helm cm-push {} "$CI_PROJECT_NAME" \;
