---
stages:
  - test
  - build
  - post-test
  - publish

variables:
  CT_IMAGE: quay.io/helmpack/chart-testing:latest

include:
  - component: $CI_SERVER_FQDN/ci/sast/sast@1
  - component: $CI_SERVER_FQDN/ci/sast/iac@1
  - component: $CI_SERVER_FQDN/ci/sast/datadog@1
  - component: $CI_SERVER_FQDN/ci/sast/bearer@1
  - component: $CI_SERVER_FQDN/ci/secret-detection/sd@1
  - component: $CI_SERVER_FQDN/ci/dependency-scanning/ds@1
  - component: $CI_SERVER_FQDN/ci/golang/init-vet@1
  - component: $CI_SERVER_FQDN/ci/golang/lint@1
  - component: $CI_SERVER_FQDN/ci/golang/test@1
  - component: $CI_SERVER_FQDN/ci/docker/build-buildah@3
    inputs:
      ci_image_name: manager
      ci_image_tags: latest,$CI_COMMIT_REF_NAME
      dockerfile_path: Dockerfile
  - component: $CI_SERVER_FQDN/ci/container-scanning/cs@1
    inputs:
      default_branch_image: $CI_REGISTRY_IMAGE/manager:latest
      application_repository: $CI_REGISTRY_IMAGE/manager
      application_tag: latest
  - component: $CI_SERVER_FQDN/ci/golang/build-binaries@1
    inputs:
      working_dir: cmd/manager

.build rules: &build-rules
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - Dockerfile
        - .gitlab-ci.yml
        - go.mod
        - "**/*.go"
        - $CI_CONFIG_PATH

build container image:
  <<:
    - *build-rules

create manifest:
  <<:
    - *build-rules

compile binaries:
  <<:
    - *build-rules
  script:
    - build_binary "ckic-manager-$VERSION" linux amd64
    - build_binary "ckic-manager-$VERSION" linux arm64

container scanning:
  <<: *build-rules
  needs:
    - job: build container image
    - job: create manifest

.chart build and publish rules: &chart-build-and-publish-rules
  rules:
    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - chart/**/*
        - $CI_CONFIG_PATH

validate + lint (helm chart):
  <<:
    - *chart-build-and-publish-rules
  stage: test
  image: $CT_IMAGE
  script:
    - cd "chart" || exit
    - ct lint --validate-chart-schema --validate-yaml --chart-dirs . --charts . --debug --validate-maintainers=false

publish helm chart to gitlab registry:
  <<:
    - *chart-build-and-publish-rules
  stage: publish
  image: $CT_IMAGE
  needs:
    - job: validate + lint (helm chart)
    - job: kics
      optional: true
  script:
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add --username gitlab-ci-token --password "$CI_JOB_TOKEN" "$CI_PROJECT_NAME" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/helm/stable"
    - helm package ./chart --destination ./packages
    - find ./packages -name "*.tgz" -print -exec helm cm-push {} "$CI_PROJECT_NAME" \;
