---
kind: ConfigMap
apiVersion: v1

metadata:
  name: caddy-default-config
  labels:
    {{- include "ckic-manager.labels" . | nindent 4 }}

data:
  Caddyfile: |-
{{ .Values.defaultCaddyConfig | indent 4 }}
