---
kind: Deployment
apiVersion: apps/v1

metadata:
  name: {{ include "ckic-manager.fullname" . }}
  labels:
    {{- include "ckic-manager.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ckic-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "ckic-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ckic-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.image }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--node-label={{ .Values.config.nodeLabel }}"
            - "--config-map={{ .Values.config.configMapName }}"
            - "--config-namespace={{ .Values.config.configMapNamespace }}"
            - "--comm-method={{ .Values.config.communicationMethod }}"
            - "--log-level={{ .Values.config.logLevel }}"
            - "--caddy-image={{ .Values.config.caddyImage }}"
            - "--enable-loadbalancer={{ .Values.config.enableLoadBalancer }}"
            - "--prefer-saved-state={{ .Values.config.preferSavedState }}"
            - "--env-secret={{ .Values.config.secretName }}"
            {{- range .Values.config.secretEnvKeys }}
            - "--env-keys={{ . }}"
            {{- end }}
            {{- if .Values.config.dataVolumePVC }}
            - "--data-pvc={{ .Values.config.dataVolumePVC }}"
            {{- end }}
            {{- if .Values.config.configVolumePVC }}
            - "--config-pvc={{ .Values.config.configVolumePVC }}"
            {{- end }}
            {{- range .Values.config.externalEndpoints }}
            - "--external-endpoints={{ . }}"
            {{- end }}
            - "--use-host-network={{ .Values.config.useHostNetwork }}"
            {{- if .Values.config.caddyAdminOriginKey }}
            - "--caddy-admin-origin-key={{ .Values.config.caddyAdminOriginKey }}"
            {{- end }}
            - "--http-host-port={{ .Values.config.httpHostPort }}"
            - "--https-host-port={{ .Values.config.httpsHostPort }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
