---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: ckic
  namespace: ckic-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: pod-reader

rules:
  - apiGroups: [""]
    resources: ["services", "secrets", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: pod-reader-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-reader

subjects:
  - kind: ServiceAccount
    name: ckic
    namespace: ckic-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: configmap-reader-and-writer

rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: configmap-reader-and-writer-binding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configmap-reader-and-writer

subjects:
  - kind: ServiceAccount
    name: ckic
    namespace: ckic-system
